# Generated by Django 3.2.5 on 2021-08-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='city',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='file',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_city',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='pin',
        ),
        migrations.AddField(
            model_name='resume',
            name='about',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='resume',
            name='clg',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='comp1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='comp2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='degree',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='exp',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='resume',
            name='grades',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='interest',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='resume',
            name='proj1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='proj2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='role',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100),
        ),
    ]
