# Generated by Django 3.2.5 on 2021-08-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_auto_20210801_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='comp1',
            new_name='certificate',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='comp2',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='proj1',
            new_name='organisation',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='proj2',
            new_name='proj',
        ),
    ]
